server:
  port: 8081
user:
  userServicePath: http://localhost:8080/findById/
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
  #      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: simple-movie