
spring:
  redis:
    shiro:
      host: 192.168.255.128
      port: 6379
      timeout: 0
      password:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud_simple?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root123
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
  application:
    name: simple-user
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
#      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

server:
  port: 8080
